name: 'Sanity Runtime Deploy'
description: 'Deploy Sanity blueprints using the @sanity/runtime-cli'
branding:
  icon: 'upload-cloud'
  color: 'red'

inputs:
  sanity_token:
    description: 'Sanity API token with deploy permissions'
    required: true
  project_id:
    description: 'Sanity project ID'
    required: false
  dataset:
    description: 'Sanity dataset name'
    required: false
    default: 'production'
  blueprint_path:
    description: 'Path to the blueprint configuration'
    required: false
    default: '.'

runs:
  using: 'node20'
  main: 'dist/index.js'
