name: 'Sanity Blueprints Plan Action'
description: 'Show Sanity blueprints plans using the @sanity/runtime-cli'
branding:
  icon: 'edit-3'
  color: 'purple'

inputs:
  sanity-token:
    description: 'Sanity API token with permissions'
    required: true
  project-id:
    description: 'Sanity project ID (required if organization-id is not provided)'
    required: false
  organization-id:
    description: 'Sanity organization ID (required if project-id is not provided)'
    required: false
  stack-id:
    description: 'Blueprint stack ID to interact with'
    required: true
  working-directory:
    description: 'Working directory that contains your blueprints and functions'
    required: false
    default: '.'

outputs:
  plan:
    description: 'Output of the blueprints plan'
    value: ${{ steps.plan.outputs.result }}

runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    # checkout above will lose reference to node_modules in CI
    # this step ensures we have the dependencies we need
    - name: Install dependencies
      shell: bash
      run: |
        npm install @sanity/blueprints @sanity/functions
        
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.organization-id }}" ] && [ -z "${{ inputs.project-id }}" ]; then
          echo "‼️Missing either a \`project-id\` or an \`organization-id\`."
          exit 1
        fi

    - name: Plan Changes
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory || '.' }}
      env:
        SANITY_AUTH_TOKEN: ${{ inputs.sanity-token }}
        SANITY_BLUEPRINT_STACK_ID: ${{ inputs.stack-id }}
        SANITY_ORGANIZATION_ID: ${{ inputs.organization-id }}
        SANITY_PROJECT_ID: ${{ inputs.project-id }}
      run: |
        echo "Running sanity blueprints plan..."
        PLAN_OUTPUT=$(npx -y @sanity/runtime-cli blueprints plan)
        echo "result<<EOF" >> $GITHUB_OUTPUT
        echo "$PLAN_OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Output Plan Details To PR Comment
      uses: actions/github-script@v8
      with:
        script: |
          const planOutput = `${{ steps.plan.outputs.result }}`;
          const prNumber = context.issue.number;
          
          // Unique identifier to find this comment
          const commentIdentifier = '<!-- sanity-blueprints-plan -->';      
          
          const commentBody = `${commentIdentifier}
            ## Sanity Blueprints Deployment Plan
            <details>
              <summary>View planned changes</summary>
              <pre>${planOutput}</pre>
            </details>
          `;
          
          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            ...context.repo,
            issue_number: prNumber,
          });

          const existingComment = comments.find(comment =>
            comment.body?.includes(commentIdentifier)
          );
      
          if (existingComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              ...context.repo,
              comment_id: existingComment.id,
              body: commentBody,
            });
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              ...context.repo,
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody,
            });
          }