name: Test Plan Action for Organizations
on:
  pull_request:
    paths:
      - 'plan/**'
      - 'tests/**'
      - '.github/workflows/test-plan.yml'

env:
  SANITY_INTERNAL_ENV: 'staging'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "Running integration test for org level plan action"

      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci
        working-directory: ./tests/plan-org

      - name: Integration Test
        uses: ./plan
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          sanity-token: ${{ secrets.SANITY_ORG_TOKEN }}
          stack-id: ${{ secrets.STACK_ID }}
          organization-id: ${{ secrets.ORGANIZATION_ID }}
          working-directory: "./tests/plan-org"