name: Test Deploy Action for Organizations
on:
  pull_request:
    paths:
      - 'deploy/**'
      - 'tests/**'
      - '.github/workflows/test-org-deploy.yml'

env:
  SANITY_INTERNAL_ENV: 'staging'

jobs:
  test-org-scope:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "Running integration test for Deploy action"

      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci
        working-directory: ./tests/deploy-org

      - name: Integration Test
        uses: ./deploy
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          sanity-token: ${{ secrets.SANITY_ORG_TOKEN }}
          stack-id: ${{ secrets.ORG_STACK_ID }}
          organization-id: ${{ secrets.ORGANIZATION_ID }}
          working-directory: "./tests/deploy-org"